### ISSUE TITLE
Set migrationPath=“@vendor/

### ISSUE THREAD

**Issue by umbalaconmeogia** [giannisdag/yii2-check-login-attempts#2]
Add @ before `vendor/` make the migrate command more flexible, so that it can run even when vendor directory is not in the app root directory.
```shell
php yii migrate --migrationPath="@vendor/giannisdag/yii2-check-login-attempts/src/migrations"  --interactive=0
```

**Comment by giannisdag** [comment]
fixed, thank you for your suggestions
